<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Promise</title>
</head>
<body>
<script>
  function handleClick () {
    return new Promise ((resolve, reject) => {
      setTimeout(() => {
        reject('Erro inesperado')//ao chamar o reject invés do resolve, nossa função cairá no catch
      }, 5000)
    })
  }

  const result = handleClick()
    .then(res => {
      console.log(123 === res)
      console.log('finalizou')
      return 'batata'
    })
    .catch(err => {
      console.log('houve um erro')
      console.log(err)
    })
</script>
</body>
</html>